export const GET_PLACES = "GET_PLACES";
export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const GET_PLACES_FAILED = "GET_PLACES_FAILED";
export const GET_PLACES_RECOMMENDED = "GET_PLACES_RECOMMENDED";
export const GET_PLACES_RECOMMENDED_SUCCESS = "GET_PLACES_RECOMMENDED_SUCCESS";
export const GET_PLACES_RECOMMENDED_FAILED = "GET_PLACES_RECOMMENDED_FAILED";